# Generated by Django 3.0.3 on 2020-03-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200302_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_product', to='app.Company'),
        ),
    ]
