# Generated by Django 3.0.3 on 2020-03-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200302_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('id', 'company', 'gst')},
        ),
    ]
